title: Camp.TCC
author:
  name: Techno Culture Club
  email: 'ariel@technoculture.club'
metadata:
    description: 'Camp.TCC is a series of collaborative workshops on 3D printing and other exciting technologies.'

